package main

import (
	"bufio"
	"compress/gzip"
	"fmt"
	"os"
	"slices"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/Vilsol/timeless-jewels/calculator"
	"github.com/Vilsol/timeless-jewels/data"
)

// TestLegionDrawsMatchPathOfBuilding pins legion jewels (types 1-6) to plain-modulo bounded
// draws. PoB's legion LUTs were generated by a C# port that draws `v % n`, so the MSVC
// rejection draw Abyss uses must not leak into them. The D records are every (type, seed, node)
// in the full legion sweep where the two draws produce different output (keys from
// comparing both draws over every seed and every NodeIndexMapping node; expected values from
// testdata/legion/dump_fixture.lua); the N records are neighbours where they agree, so the
// grader is shown to work on records the draw cannot decide.
//
// PoB's legion LUT stores less than Calculate returns: for types 2-6 only the id of a notable's
// replacement or first addition, for Glorious Vanity either a replacement id with its rolls (2 or 3 bytes) or the
// addition ids followed by their first rolls (6 or 8 bytes, without the replacement a
// legacy/might node also carries).
func TestLegionDrawsMatchPathOfBuilding(t *testing.T) {
	byGraphID := make(map[uint32]*data.PassiveSkill, len(data.PassiveSkills))
	for _, p := range data.PassiveSkills {
		if _, ok := byGraphID[p.PassiveSkillGraphID]; !ok {
			byGraphID[p.PassiveSkillGraphID] = p
		}
	}

	f, err := os.Open("testdata/legion/legion_draws.txt.gz")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	zr, err := gzip.NewReader(f)
	if err != nil {
		t.Fatal(err)
	}

	lines := 0
	read := make(map[string]int)
	failures := make(map[string]int)
	neighbours := make(map[data.JewelType]int)

	sc := bufio.NewScanner(zr)
	for sc.Scan() {
		lines++
		fields := strings.Fields(sc.Text())
		if len(fields) != 5 || (fields[0] != "D" && fields[0] != "N") {
			t.Fatalf("bad fixture line %q", sc.Text())
		}
		jt, err1 := strconv.Atoi(fields[1])
		seed, err2 := strconv.Atoi(fields[2])
		node, err3 := strconv.Atoi(fields[3])
		want, err4 := parseLegionLUT(fields[4])
		if err1 != nil || err2 != nil || err3 != nil || err4 != nil || len(want) == 0 {
			t.Fatalf("bad fixture line %q", sc.Text())
		}
		jewel := data.JewelType(jt)
		read[fields[0]]++
		if fields[0] == "N" {
			neighbours[jewel]++
		}

		passive := byGraphID[uint32(node)]
		if passive == nil {
			t.Fatalf("node %d is not a passive skill", node)
		}
		// The LUT does not depend on the conqueror; any fixed one will do.
		conquerors := make([]string, 0, len(data.TimelessJewelConquerors[jewel]))
		for c := range data.TimelessJewelConquerors[jewel] {
			conquerors = append(conquerors, string(c))
		}
		sort.Strings(conquerors)

		got := calculator.Calculate(passive.Index, uint32(seed), jewel, data.Conqueror(conquerors[0]))
		if !legionMatchesLUT(jewel, got, want) {
			failures[fields[0]]++
			t.Errorf("%s %s seed %d node %d (%s): got %s, PoB LUT %v", fields[0], jewel, seed, node, passive.Name, legionString(got), want)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}

	if lines == 0 || read["D"]+read["N"] != lines {
		t.Fatalf("read %d D + %d N records from %d fixture lines", read["D"], read["N"], lines)
	}
	for jt := data.GloriousVanity; jt <= data.HeroicTragedy; jt++ {
		if neighbours[jt] < 10 {
			t.Errorf("%s: %d neighbour records, want at least 10", jt, neighbours[jt])
		}
	}
	if read["D"] != 100 {
		t.Errorf("expected 100 deciding records, got %d", read["D"])
	}
	if failures["D"]+failures["N"] > 0 {
		t.Errorf("%d of %d deciding and %d of %d neighbour records differ from PoB", failures["D"], read["D"], failures["N"], read["N"])
	}
}

func parseLegionLUT(s string) ([]int, error) {
	out := []int{}
	for _, v := range strings.Split(s, ",") {
		n, err := strconv.Atoi(v)
		if err != nil {
			return nil, fmt.Errorf("parsing %q: %w", v, err)
		}
		out = append(out, n)
	}
	return out, nil
}

func legionMatchesLUT(jewel data.JewelType, info data.AlternatePassiveSkillInformation, lut []int) bool {
	replaced := info.AlternatePassiveSkill != nil
	adds := info.AlternatePassiveAdditionInformations

	if jewel != data.GloriousVanity {
		switch {
		case replaced:
			return int(info.AlternatePassiveSkill.Index+pobTimelessJewelAdditions) == lut[0]
		case len(adds) > 0:
			return int(adds[0].AlternatePassiveAddition.Index) == lut[0]
		}
		return false
	}

	switch len(lut) {
	case 2, 3:
		if !replaced || len(adds) > 0 || int(info.AlternatePassiveSkill.Index+pobTimelessJewelAdditions) != lut[0] {
			return false
		}
		rolls := make([]int, len(info.StatRolls))
		for i, r := range info.StatRolls {
			rolls[i] = int(r)
		}
		k := len(lut) - 1
		return len(rolls) >= k && slices.Equal(rolls[:k], lut[1:]) && !slices.ContainsFunc(rolls[k:], func(r int) bool { return r != 0 })
	case 6, 8:
		k := len(lut) / 2
		if len(adds) != k {
			return false
		}
		for i, a := range adds {
			if int(a.AlternatePassiveAddition.Index) != lut[i] || len(a.StatRolls) == 0 || int(a.StatRolls[0]) != lut[k+i] {
				return false
			}
		}
		return true
	}
	return false
}

func legionString(info data.AlternatePassiveSkillInformation) string {
	s := ""
	if info.AlternatePassiveSkill != nil {
		s += fmt.Sprintf("%d:%v", info.AlternatePassiveSkill.Index+pobTimelessJewelAdditions, info.StatRolls)
	}
	for _, a := range info.AlternatePassiveAdditionInformations {
		s += fmt.Sprintf(" +%d:%v", a.AlternatePassiveAddition.Index, a.StatRolls)
	}
	if s == "" {
		return "-"
	}
	return s
}
